"""Fix is_published on Course, move metadata from Lesson to Course

Revision ID: 2a709819db6c
Revises: f742c27e3ddf
Create Date: 2025-07-27 21:59:48.836057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a709819db6c'
down_revision = 'f742c27e3ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.drop_column('published')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('tags')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('duration')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('category')
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
