"""Add extra fields to Lesson

Revision ID: f742c27e3ddf
Revises: 
Create Date: 2025-07-27 19:13:59.552880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f742c27e3ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_request', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('head_admin')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('tags')
        batch_op.drop_column('duration')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('category')

    with op.batch_alter_table('admin_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_admin', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
